# Generated by Django 5.0.6 on 2024-06-02 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_alert_sensor_alter_data_co2_alter_data_pm10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sensors.sensor'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='co2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='pm10',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='pm25',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='sensors.sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], max_length=50),
        ),
    ]
